# Generated by Django 2.2.4 on 2019-08-25 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bode',
            new_name='body',
        ),
    ]
