# Generated by Django 2.2.6 on 2019-12-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191202_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.TextField(db_index=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
