# Generated by Django 2.2.6 on 2020-01-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20191205_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
